version: '3.7'

# Shared settings for app and celery workers
x-pili-common: &pili-common
  image: pili:${PILI_VERSION:-latest}
  init: true
  environment:
    - DATABASE_URL=postgresql://pili:pili@db/pili
    - SSL_DISABLE=1
    - FLASK_CONFIG=unix
    - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
    - CELERY_RESULT_BACKEND=redis://redis:6379/10
    - SECRET_KEY=oos6upuJahG3Eerezo2Apha4CooPiex7


services:
  # Application Configuration
  db:
    image: postgres
    init: true
    restart: always
    environment:
      POSTGRES_PASSWORD: pili
      POSTGRES_USER: pili
      POSTGRES_DB: pili

  rabbitmq:
    image: rabbitmq:3-management
    init: true
    ports:
      - 15672:15672
      - 5672:5672

  redis:
    image: redis:5-alpine
    init: true

  celery:
    <<: *pili-common
    command: celery worker -A celery_worker.celery --loglevel=info
    links:
      - rabbitmq
      - redis

  pili:
    <<: *pili-common
    build: .
    command: ./docker-entrypoint.sh
    links:
      - db
      - celery
      - redis
    ports:
      - 5000:5000

    stdin_open: true
    tty: true

    logging:
      driver: json-file
      options:
        max-size: 10k

    volumes:
      - ./pili:/pili/pili
      - ./etc:/pili/etc
      - ./tests:/pili/tests
      - ./setup.cfg:/pili/setup.cfg
      - ./setup.py:/pili/setup.py
      - ./manage.py:/pili/manage.py
