version: '3.7'

# Shared settings for app and celery workers
x-pili-common: &pili-common
  image: pili:${PILI_VERSION:-latest}
  init: true
  environment:
    - PILI_CONFIG=${PILI_CONFIG:-testing}
  env_file:
    - ./etc/env/${PILI_CONFIG:-development}.env


services:
  # Application Configuration
  db:
    image: postgres
    init: true
    restart: always
    environment:
      POSTGRES_PASSWORD: pili
      POSTGRES_USER: pili
      POSTGRES_DB: pili

  rabbitmq:
    image: rabbitmq:3-management
    init: true
    ports:
      - 15672:15672
      - 5672:5672

  redis:
    image: redis:5-alpine
    init: true

  celery:
    # scale workers when needed
    # docker-compose up --scale celery=3
    <<: *pili-common
    command: celery worker -A pili.entrypoints.celery.celery --loglevel=info
    links:
      - rabbitmq
      - redis

  flower:
    <<: *pili-common
    command: flower -A pili.entrypoints.celery.celery --loglevel=info
    links:
      - rabbitmq
    ports:
      - 5678:5678

  pili:
    <<: *pili-common
    build: .
    command: >
      sh -c "echo '--> Provision DB' &&
             pili --config=${PILI_CONFIG} provision --db_init --db_migrate --db_upgrade --db_prepopulate &&
             echo '--> Run uWSGI' &&
             pili --config=${PILI_CONFIG} uwsgi --section=${PILI_CONFIG}"
    links:
      - db
      - celery
      - redis
    ports:
      - 8080:8080

    stdin_open: true
    tty: true

    logging:
      driver: json-file
      options:
        max-size: 10k

    volumes:
      - ./pili:/app/pili
      - ./etc:/app/etc
      - ./tests:/app/tests
      - ./setup.cfg:/app/setup.cfg
      - ./setup.py:/app/setup.py
