version: '3'
services:
  app:
    build:
      context: .
    image: pilosus/pili
    environment:
      FLASK_INIT: 1
      FLASK_DEPLOY: 1
      FLASK_CONFIG: testing
      SECRET_KEY: testing
      SSL_DISABLE: 1
    command: ./docker-entrypoint.sh
