apiVersion: apps/v1
kind: Deployment
metadata:
  name: pili
spec:
  selector:
    matchLabels:
      app: pili
      tier: backend
  replicas: 3
  template:
    metadata:
      labels:
        app: pili
        tier: backend
    spec:
      containers:
      - name: pili
        image: registry.pilosus.org/pilosus/pili:0.2.3
        command: ["./docker-entrypoint.sh"]
        envFrom:
          - configMapRef:
              name: pili-config
        ports:
          - name: uwsgi
            containerPort: 8080
      imagePullSecrets:
        - name: registry-credentials
      restartPolicy: Always
