# See https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/
kind: PersistentVolume
apiVersion: v1
metadata:
  name: rabbitmq-pv-volume
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    # $ minikube ssh
    # $ sudo mkdir -p /mnt/data/rabbitmq
    path: "/mnt/data/rabbitmq"
