# https://github.com/helm/charts/tree/master/stable/postgresql
postgresqlUsername: pili
postgresqlPassword: chah3Xie
postgresqlDatabase: pili

image:
  registry: docker.io
  repository: bitnami/postgresql
  tag: 10.7.0-r68

replication:
  enabled: true
  slaveReplicas: 1
  synchronousCommit: "off"
  user: repl_user
  password: Fah4dohZ
