"""empty message

Revision ID: 0110b4a52e61
Revises: 3bb5e755df4
Create Date: 2016-04-16 17:29:54.404017

"""

# revision identifiers, used by Alembic.
revision = '0110b4a52e61'
down_revision = '3bb5e755df4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
