"""empty message

Revision ID: 04be9cd75c20
Revises: bdc56eae795f
Create Date: 2016-04-25 11:08:24.283264

"""

# revision identifiers, used by Alembic.
revision = '04be9cd75c20'
down_revision = 'bdc56eae795f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('featured', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_categories_featured'), ['featured'], unique=False)

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_featured'))
        batch_op.drop_column('featured')

    ### end Alembic commands ###
