"""empty message

Revision ID: 060fb4c84f64
Revises: 15c724b06a17
Create Date: 2016-08-07 15:21:59.131849

"""

# revision identifiers, used by Alembic.
revision = '060fb4c84f64'
down_revision = '15c724b06a17'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('invited', sa.Boolean(), nullable=True))
    op.drop_column('users', 'invited_on')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('invited_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('users', 'invited')
    ### end Alembic commands ###
