"""empty message

Revision ID: 15c724b06a17
Revises: 203e2014a5d1
Create Date: 2016-08-07 14:40:58.754893

"""

# revision identifiers, used by Alembic.
revision = '15c724b06a17'
down_revision = '203e2014a5d1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('invited_on', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'invited_on')
    ### end Alembic commands ###
