"""empty message

Revision ID: 2b2699cca1e
Revises: 42253197d94
Create Date: 2016-03-09 17:36:23.096712

"""

# revision identifiers, used by Alembic.
revision = '2b2699cca1e'
down_revision = '42253197d94'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('img', sa.String(length=128), nullable=True))
    op.add_column('categories', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index('ix_categories_timestamp', 'categories', ['timestamp'], unique=False)
    op.add_column('posts', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('img', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'img')
    op.drop_column('posts', 'category_id')
    op.drop_index('ix_categories_timestamp', 'categories')
    op.drop_column('categories', 'timestamp')
    op.drop_column('categories', 'img')
    ### end Alembic commands ###
