"""empty message

Revision ID: 42253197d94
Revises: 2354762e5
Create Date: 2016-03-09 15:40:18.803732

"""

# revision identifiers, used by Alembic.
revision = '42253197d94'
down_revision = '2354762e5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('alias', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias')
    )
    op.create_table('tagifications',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('tag_id', 'post_id')
    )
    op.drop_table('comments')
    op.drop_table('follows')
    op.drop_table('replies')
    op.drop_table('classifications')
    op.add_column('categories', sa.Column('body', sa.Text(), nullable=True))
    op.add_column('categories', sa.Column('body_html', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('featured', sa.Boolean(), nullable=True))
    op.create_index('ix_posts_featured', 'posts', ['featured'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_posts_featured', 'posts')
    op.drop_column('posts', 'featured')
    op.drop_column('categories', 'body_html')
    op.drop_column('categories', 'body')
    op.create_table('classifications',
    sa.Column('category_id', sa.INTEGER(), nullable=False),
    sa.Column('post_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('category_id', 'post_id')
    )
    op.create_table('replies',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('parent_id', sa.INTEGER(), nullable=True),
    sa.Column('replier_id', sa.INTEGER(), nullable=False),
    sa.Column('repliee_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['repliee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['replier_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'replier_id', 'repliee_id')
    )
    op.create_table('follows',
    sa.Column('follower_id', sa.INTEGER(), nullable=False),
    sa.Column('followed_id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    op.create_table('comments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.TEXT(), nullable=True),
    sa.Column('body_html', sa.TEXT(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('disabled', sa.BOOLEAN(), nullable=True),
    sa.Column('author_id', sa.INTEGER(), nullable=True),
    sa.Column('post_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tagifications')
    op.drop_table('tags')
    ### end Alembic commands ###
