"""empty message

Revision ID: 68a5076fa0e0
Revises: 4f95be43ba99
Create Date: 2016-07-28 20:05:42.077023

"""

# revision identifiers, used by Alembic.
revision = '68a5076fa0e0'
down_revision = '4f95be43ba99'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'suspended')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('suspended', sa.BOOLEAN(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
