"""empty message

Revision ID: 732e78526d34
Revises: 68a5076fa0e0
Create Date: 2016-07-29 10:04:18.991120

"""

# revision identifiers, used by Alembic.
revision = '732e78526d34'
down_revision = '68a5076fa0e0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tags_author_id_fkey', 'tags', type_='foreignkey')
    op.drop_column('tags', 'author_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('tags_author_id_fkey', 'tags', 'users', ['author_id'], ['id'])
    ### end Alembic commands ###
