"""empty message

Revision ID: 7c4c60c7f5da
Revises: 1768679b7c13
Create Date: 2016-07-26 11:33:06.451498

"""

# revision identifiers, used by Alembic.
revision = '7c4c60c7f5da'
down_revision = '1768679b7c13'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('seen', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'seen')
    ### end Alembic commands ###
