"""empty message

Revision ID: b1b1f0b1b2f1
Revises: 7c4c60c7f5da
Create Date: 2016-07-26 12:20:13.925278

"""

# revision identifiers, used by Alembic.
revision = 'b1b1f0b1b2f1'
down_revision = '7c4c60c7f5da'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('read', sa.Boolean(), nullable=True))
    op.drop_column('comments', 'seen')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('seen', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('comments', 'read')
    ### end Alembic commands ###
