"""empty message

Revision ID: ba18ad5630ef
Revises: 732e78526d34
Create Date: 2016-07-29 10:26:14.415307

"""

# revision identifiers, used by Alembic.
revision = 'ba18ad5630ef'
down_revision = '732e78526d34'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tags', 'users', ['author_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_column('tags', 'author_id')
    ### end Alembic commands ###
