"""empty message

Revision ID: bdc56eae795f
Revises: None
Create Date: 2016-04-22 18:01:28.423922

"""

# revision identifiers, used by Alembic.
revision = 'bdc56eae795f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###

