"""empty message

Revision ID: bef2f2ee48d9
Revises: None
Create Date: 2016-06-06 20:39:10.917922

"""

# revision identifiers, used by Alembic.
revision = 'bef2f2ee48d9'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('commenting', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_posts_commenting'), 'posts', ['commenting'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_commenting'), table_name='posts')
    op.drop_column('posts', 'commenting')
    ### end Alembic commands ###
