"""empty message

Revision ID: cf194b2c8cc8
Revises: ba18ad5630ef
Create Date: 2016-07-29 20:28:41.759551

"""

# revision identifiers, used by Alembic.
revision = 'cf194b2c8cc8'
down_revision = 'ba18ad5630ef'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('description', sa.String(length=160), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'description')
    ### end Alembic commands ###
