"""empty message

Revision ID: de6a1831e31b
Revises: bef2f2ee48d9
Create Date: 2016-07-20 18:26:16.201386

"""

# revision identifiers, used by Alembic.
revision = 'de6a1831e31b'
down_revision = 'bef2f2ee48d9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('screened', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'screened')
    ### end Alembic commands ###
