#!/bin/bash

############################################################
### Git post-receive hook example for deploying Pili App ###
############################################################

### See alo
### https://www.digitalocean.com/community/tutorials/how-to-use-git-hooks-to-automate-development-and-deployment-tasks

while read oldrev newrev ref
do
    if [[ $ref =~ .*/master$ ]];
    then
	echo "Master ref received. Deploying master branch to production..."
	git --work-tree=/var/www/pili --git-dir=/home/git/pili.git checkout -f
    else
	echo "Ref $ref successfully received. Doing nothing: only the master branch may be deployed on this server."
    fi
done
